apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: medium-app
spec:
  rules:
  - host: mediumapp.zhbert.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: medium-app-frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: medium-app-backend
            port:
              number: 8080
  tls:
    - hosts:
        - mediumapp.zhbert.ru
      secretName: medium-app-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: medium-app
  namespace: medium-app
spec:
  secretName: medium-app-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
  - mediumapp.zhbert.ru
